version: '3.8'

services:
  postgres:
    image: postgres:12
    container_name: kate-history-postgres
    environment:
      POSTGRES_USER: bot_user
      POSTGRES_PASSWORD: bot_password
      POSTGRES_DB: bot_db
    ports:
      - "5555:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  kate-history-bot:
    build: .
    container_name: kate-history-bot
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bot_db
      SPRING_DATASOURCE_USERNAME: bot_user
      SPRING_DATASOURCE_PASSWORD: bot_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: unless-stopped

volumes:
  postgres_data: